version: '2'

services:
  server:
    image: lomo/netxms-server
    ports:
    - "4700:4700"
    - "4701:4701"

  webui:
    image: lomo/netxms-webui
    ports:
    - "8080:8080"
    environment:
    - "NETXMS_SERVER=server"

  console:
    build: lomo/netxms-nxmc
    environment:
    - "DISPLAY=$DISPLAY"
    volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix"

  agent:
    image: lomo/netxms-nxagent
    environment:
    - "NXAGENT_CONFIG=MasterServer=server\nLogFile=/var/log/nxagentsome.log\nEnableProxy=yes\nEnableSNMPProxy=yes"
    - "NXAGENT_MASTERSERVERS=server"
    - "NXAGENT_REGISTERSERVER=server"
