name: Docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Web UI
      with:
        image: ghcr.io/${{ github.repository_owner }}/netxms_webui
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }} 
        dockerfile: webui/Dockerfile