name: Build Docker Images

on: [push]

jobs:

  WebUI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Web UI
      with:
        image: netxms_webui
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }} 
        dockerfile: webui/Dockerfile

  WebUIREST:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Web UI
      with:
        image: netxms_webuirest
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }} 
        dockerfile: webuirest/Dockerfile